#Versão do jdk usado/instalado no projeto maquina
#FROM openjdk:25-jdk-oracle
# Criando um pasta chamada app
#RUN #mkdir /app
# Mudando para o diretório criado
#WORKDIR /app
# Ele vai pega o arquivo que o mavem criou e colocará nesse
# diretorio tudo que tiver .jar onde irá renomear para app
#COPY target/*.jar /app/app.jar
# Iniciar o projeto
#CMD ["java","-jar","/app/app.jar"]
