#version: '3.1'
version: '3.8'

services:
  db:
    #ultima/versão suportada e não a usada no projeto
    #image: mysql:9.2.0
    image: mysql:8.4.6
    #Quando é gerado ele reset os dados do banco para isso não acontecer salvamos
    volumes:
      - dbbase:/var/lib/mysql
      #Setando a porta do mysql
    ports:
      - "3306:3306"
    #Vai reiniciar automaticamente o projeto/maquina que estiver rodando
    #    restart: always
    environment:
      #Nm do banco usado
      MYSQL_DATABASE: carros
      #Senha do banco
      MYSQL_ROOT_PASSWORD: root123

  phpmyadmin:
    image: phpmyadmin
    #    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    #    restart: always
    ports:
      - 8080:80

    #    environment:
    #        - PMA_ARBITRARY=1
#Aqui deixa a senha e user setado e indo direto para pg sem precisar logar
#      PMA_HOST: db
#      PMA_USER: root
#      PMA_PASSWORD: root123

#Criamos a variável para salvar os dodos
volumes:
  dbbase: